print(" ")
print("***********************************************************************************************************")
print("Author: ")
print("TTTTT  EEEEE  N   N   GGG   K   K   U   U")
print("  T    E      NN  N  G      K  K    U   U")
print("  T    EEE    N N N  G  GG  KKK     U   U")
print("  T    E      N  NN  G   G  K  K    U   U")
print("  T    EEEEE  N   N   GGG   K   K   UUUU")
print("https://tengkulist.web.app/")
print("Tool: Ping Test")
print("Version : v1.0_20230221")
print("***********************************************************************************************************")
print(" ")